/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package edu.au.cc.gallery;
import static spark.Spark.*;
import spark.ModelAndView;
import spark.Response;
import spark.template.handlebars.HandlebarsTemplateEngine;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello Michael!!";
    }

   private static String listUsers() {
	try {
		StringBuffer sb = new StringBuffer();
		UserDAO dao = Postgres.getUserDAO();
		for (User u: dao.getUsers())
			sb.append(u.toString()+"<br/>");
		return sb.toString();
	}
	catch (Exception e) {
		return e.getMessage();
	}
   }

   private static String addUser(String username, String password, String fullName, Response r) {
      try {
	 UserDAO dao = Postgres.getUserDAO();
	 dao.addUser(new User(username, password, fullName));
	r.redirect("/users");
	return "";
      } 
     catch (Exception e) {
	  return e.getMessage();
     }
  }
    public static void main(String[] args) throws Exception{
       //System.out.println(new App().getGreeting());
	String portString = System.getenv("JETTY_PORT");
	if (portString == null || portString.equals( ""))
		port(5000);
	else 
		port(Integer.parseInt(portString));

	new Admin().addRoutes();

    }
}
