/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package edu.au.cc.gallery;
import static spark.Spark.*;
import spark.ModelAndView;
import spark.template.handlebars.HandlebarsTemplateEngine;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello Michael!!";
    }

    public static void main(String[] args) throws Exception{
       //System.out.println(new App().getGreeting());
	String portString = System.getenv("JETTY_PORT");
	if (portString == null || portString.equals( ""))
		port(5000);
	else 
		port(Integer.parseInt(portString));

	get("/hello", (req, res) -> "hello world");
	get("/admin", (req, res) -> {
		Map<String, Object> model = new HashMap<String, Object>();
		ArrayList<String> list = new ArrayList();
		ArrayList<Map> listMap = new ArrayList();
		DB db = new DB();
		list = db.listUsers();
		list.forEach((i) -> {
			Map<String, Object> temp = new HashMap<String, Object>();
			temp.put("username", i);
			listMap.add(temp);
		});
		model.put("users", listMap);
		return new HandlebarsTemplateEngine()
		.render(new ModelAndView(model, "admin.hbs"));
	});
	 get("/admin/edit", (req, res) -> {
                Map<String, Object> model = new HashMap<String, Object>();
                //model.put(db.listUser());
                return new HandlebarsTemplateEngine()
                .render(new ModelAndView(model, "edit.hbs"));
        });
	get("/admin/delete", (req, res) -> {
                Map<String, Object> model = new HashMap<String, Object>();
                //model.put(db.listUser());
                return new HandlebarsTemplateEngine()
                .render(new ModelAndView(model, "delete.hbs"));
        });
	get("/admin/add", (req, res) -> {
                Map<String, Object> model = new HashMap<String, Object>();
                //model.put(db.listUser());
                return new HandlebarsTemplateEngine()
                .render(new ModelAndView(model, "add.hbs"));
        });


    }
}
