/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;

public class App {
    public String getGreeting() {
        return "Hello Michael!!";
    }

    public static void main(String[] args) {
       // System.out.println(new App().getGreeting());
	S3.demo();
    }
}
