---
all:
  hosts:
    ec2-18-221-46-34.us-east-2.compute.amazonaws.com:
    ec2-3-133-144-30.us-east-2.compute.amazonaws.com:
    ec2-3-16-79-86.us-east-2.compute.amazonaws.com:
  children:
     al2:
      hosts:
        ec2-18-221-46-34.us-east-2.compute.amazonaws.com:
        ec2-3-133-144-30.us-east-2.compute.amazonaws.com:
        ec2-3-16-79-86.us-east-2.compute.amazonaws.com:
      vars: 
        ansible_user: ec2-user
        ansible_python_interpreter: /usr/bin/python

